module.exports = {
  JAVA:'JAVA',
  PYTHON:'PYTHON',
  JAVASCRIPT:'JAVASCRIPT',
  C:"C#",
  CPP:"C++",
  OCAML:"OCAML",
  PERL:"Perl",
  PHP:"PHP",
  ML:"Machine Learning",
  IOS:"IOS",
  ANDROID:"Android",
  UI:"UI design",
  RUBY:"Ruby",
  Matlab:"Matlab",
  GO:"Go",
  SQL:"SQL",
  NOSQL:"NoSql",
}
